@InPay__CuriousCat_BackEnd_HostAddress = http://localhost:5066

Post {{InPay__CuriousCat_BackEnd_HostAddress}}/register
Content-Type: application/json
Accept: application/json   

{
  "userName": "Miti",
  "email": "miti@miti.com",
  "phoneNumber": "+55 41 9 9999-9999",
  "password": "Miti@123456",
  "passwordConfirmation": "Miti@123456",
  "recoveryCode": "123456",
  "antiPishingCode": "87654321"
}
###

Post {{InPay__CuriousCat_BackEnd_HostAddress}}/login
Content-Type: application/json
Accept: application/json   

{
  "email": "miti@miti.com",
  "password": "Miti@123456"
}

###

GET {{InPay__CuriousCat_BackEnd_HostAddress}}/user/6d96b8e3-033d-473e-8c4e-323b2ef31a40
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6Ik1pdGkiLCJJZCI6IjliZGM2OTA1LTQyNmItNDQ3YS1iYjc2LTljYjEyYWIxZDc2MiIsIklzQWRtaW4iOiJUcnVlIiwiZXhwIjoxNzExMTc4NTIxfQ.EncEEz15NhFNpqKVZCdAwYgEG1W0W7vMt2ejg_ywFBk

###
GET {{InPay__CuriousCat_BackEnd_HostAddress}}/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6Ik1pdGkiLCJJZCI6IjliZGM2OTA1LTQyNmItNDQ3YS1iYjc2LTljYjEyYWIxZDc2MiIsIklzQWRtaW4iOiJUcnVlIiwiZXhwIjoxNzExMTc5NzgyfQ.-4tG04uI_4I0KM_XgLtF8JVWpdZt8uvb7c3H9yQFp0o

###
