@InPay__CuriousCat_BackEnd_HostAddress = http://localhost:5066
@authTOkenNormalUser = {{loginNormalUser.response.body.userToken}}
@authTOkenAdmin = {{loginADmin.response.body.userToken}}

@authTokenLoggedPFAcc = {{LoginAccPF.response.body.AccToken}}
@authTokenLoggedPJAcc = {{LoginAccPJ.response.body.AccToken}}

Post {{InPay__CuriousCat_BackEnd_HostAddress}}/register
Content-Type: application/json
Accept: application/json   

{
  "userName": "Miti",
  "email": "miti@miti.com",
  "phoneNumber": "+55 41 9 9999-9999",
  "password": "Miti@123456",
  "passwordConfirmation": "Miti@123456",
  "recoveryCode": "123456",
  "antiPishingCode": "87654321"
}

###

# @name loginNormalUser
Post {{InPay__CuriousCat_BackEnd_HostAddress}}/login
Content-Type: application/json
Accept: application/json

{
  "email": "teste@teste.com",
  "password": "Teste@123"
}

###

# @name loginADmin
Post {{InPay__CuriousCat_BackEnd_HostAddress}}/login
Content-Type: application/json
Accept: application/json

{
  "email": "miti@miti.com",
  "password": "Miti@123456"
}

###

GET {{InPay__CuriousCat_BackEnd_HostAddress}}/user/1274464d-c1d3-42fc-a84e-b48be8862382
Accept: application/json
Authorization: Bearer {{authTOkenNormalUser}}

###
GET {{InPay__CuriousCat_BackEnd_HostAddress}}/user/6d96b8e3-033d-473e-8c4e-323b2ef31a40
Accept: application/json
Authorization: Bearer {{authTOkenNormalUser}}

###

GET {{InPay__CuriousCat_BackEnd_HostAddress}}/user/6d96b8e3-033d-473e-8c4e-323b2ef31a40
Accept: application/json
Authorization: Bearer {{authTOkenAdmin}}

###

GET {{InPay__CuriousCat_BackEnd_HostAddress}}/users
Accept: application/json
Authorization: Bearer {{authTOkenNormalUser}}

###

GET {{InPay__CuriousCat_BackEnd_HostAddress}}/users
Accept: application/json
Authorization: Bearer {{authTOkenAdmin}}

###

Put {{InPay__CuriousCat_BackEnd_HostAddress}}/user/6d96b8e3-033d-473e-8c4e-323b2ef31a40
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTOkenAdmin}}

{
  "userName": "TesteAtualizado",
  "email": "testeAtualizado@teste.com",
  "phoneNumber": "+55 41 9 9999-9999"
}

###

PATCH  {{InPay__CuriousCat_BackEnd_HostAddress}}/user/6d96b8e3-033d-473e-8c4e-323b2ef31a40
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTOkenAdmin}}

{
  "userName": "TestePatched"
}

###

PUT  {{InPay__CuriousCat_BackEnd_HostAddress}}/user/6d96b8e3-033d-473e-8c4e-323b2ef31a40/changePassword
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTOkenAdmin}}

{
  "currentPassword": "Teste@123",
  "newPassword": "Teste@123Atualizado",
  "newPasswordConfirmation": "Teste@123Atualizado"
}

###

PUT  {{InPay__CuriousCat_BackEnd_HostAddress}}/user/6d96b8e3-033d-473e-8c4e-323b2ef31a40/forgotPassword
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTOkenAdmin}}

{
  "recoveryCode": "123456",
  "newPassword": "Teste@123NewPassword",
  "newPasswordConfirmation": "Teste@123NewPassword"
}

###

DELETE   {{InPay__CuriousCat_BackEnd_HostAddress}}/user/6d96b8e3-033d-473e-8c4e-323b2ef31a40/deleteUser
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTOkenAdmin}}

###

PUT    {{InPay__CuriousCat_BackEnd_HostAddress}}/user/6d96b8e3-033d-473e-8c4e-323b2ef31a40/undeleteUser
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTOkenAdmin}}

###

POST   {{InPay__CuriousCat_BackEnd_HostAddress}}/user/6d96b8e3-033d-473e-8c4e-323b2ef31a40/acc/createPFAcc
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTOkenAdmin}}

{
  "accNickName": "TestePF",
  "adress": {
    "cep": "80330-000",
    "street": "Street",
    "number": 177,
    "neighborhood": "Bairro",
    "city": "Cidade",
    "state": "Estado",
    "country": "Pais",
    "complement": "Complemento"
  },
  "accRecoveryCode": "string",
  "cpf": "123.456.789.12",
  "name": "Teste User da Silva",
  "birthDay": "1990-01-22T01:15:52.164Z"
}

###

POST   {{InPay__CuriousCat_BackEnd_HostAddress}}/user/6d96b8e3-033d-473e-8c4e-323b2ef31a40/acc/createPJAcc/
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTOkenAdmin}}

{
  "accNickName": "TestePJ",
  "adress": {
    "cep": "80330-000",
    "street": "Street",
    "number": 177,
    "neighborhood": "Bairro",
    "city": "Cidade",
    "state": "Estado",
    "country": "Pais",
    "complement": "Complemento"
  },
  "accRecoveryCode": "string",
  "cnpj": "12.345.678/0001-92",
  "companyName": "Empresa de Teste2",
  "companyEmail": "empresateste2@empresa.com",
  "password": "Empresa@teste123",
  "passwordConfirmation": "Empresa@teste123"
}

###

# @name LoginAccPF
POST    {{InPay__CuriousCat_BackEnd_HostAddress}}/user/62cf6c8b-4cfb-4489-af7b-83d2bcf7336c/acc/login
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTOkenAdmin}}

{
  "accNumber": 1235
}

###
# @name LoginAccPJ
POST   {{InPay__CuriousCat_BackEnd_HostAddress}}/user/62cf6c8b-4cfb-4489-af7b-83d2bcf7336c/acc/login
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTOkenAdmin}}

{
  "accNumber": 9263
}

###

GET    {{InPay__CuriousCat_BackEnd_HostAddress}}/user/62cf6c8b-4cfb-4489-af7b-83d2bcf7336c/acc/1235/balance
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTokenLoggedPFAcc}}

###

GET    {{InPay__CuriousCat_BackEnd_HostAddress}}/user/62cf6c8b-4cfb-4489-af7b-83d2bcf7336c/acc/9263/balance
Content-Type: application/json
Accept: application/json   
Authorization: Bearer {{authTokenLoggedPJAcc}}

###

POST    {{InPay__CuriousCat_BackEnd_HostAddress}}/deposit
Content-Type: application/json
Accept: application/json 

{
  "accNumber": 1648,
  "agency": "0001",
  "cpf": "123.456.789.12",
  "value": 500
}

###
POST    {{InPay__CuriousCat_BackEnd_HostAddress}}/deposit
Content-Type: application/json
Accept: application/json 

{
  "accNumber": 6750,
  "agency": "0001",
  "cnpj": "12.345.678/0001-92",
  "value": 500
}

###
